### ISSUE TITLE
Help getting this to run 

### ISSUE THREAD

**Issue by Gfisk25** [escalonely/AES70_OCP1_StringGenerator#1]
Hi,
this little tool is exactly what I have been looking for!
I am unable to get it to run however.
I am on macos 12.6.8
I installed Jucer and tried to make it run via xcode, but couldnt get it to work.
Is it possible to give me a hand?

Thanks

**Comment by Gfisk25** [comment]
Sorry, I just found the release ZIP

**Comment by escalonely** [comment]
Hi there!
There is indeed a zipped executable, but it is for Windows. If you are on Mac you'll have to build the tool yourself. I'm not an expert in xcode but I can try to help, if you want to do a Zoom call or similar. Where are you based on?
Cheers, B.
